### ISSUE TITLE
QT application fails when call is applied for both UXYZ call methods

### ISSUE THREAD

**Issue by thetille** [nanovna/NanoVNA-QT#24]
I recently got my nanovna v2 plus4 and tried to calibrate the unit using the QT application in Ubuntu. When i use the UXYZ and modified UXYZ method and hit apply the application crashed.

**Comment by jeff-wittrock** [comment]
Just received my nanovna v2.  I am seeing the same problem running on windows 10 x64.

**Comment by bvernoux** [comment]
Same issue reproduced with Windows 10 x64

**Comment by mtreis86** [comment]
Error in the terminal when crashing:
`terminate called after throwing an instance of 'std::runtime_error'
  what():  matrix rank is not full! should be 4, is 3
./run: line 3: 47172 Aborted                 (core dumped) LD_LIBRARY_PATH="$LIBDIR/libxavna/.libs:$LIBDIR/libxavna/xavna_mock_ui" "$@"
`

Relevant part of GDB backtrace of the coredump:
```
#5  0x00007f373c7f5f8e in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7f373c958220 <typeinfo for std::runtime_error>, 
    dest=0x7f373c80c050 <std::runtime_error::~runtime_error()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95

#6  0x00007f373e1323cf in xaxaxa::CalibrationEngine::computeCoefficients (this=0x7ffd3a460180) at /usr/include/c++/11.1.0/ext/new_allocator.h:89

#7  0x00007f373e14db68 in xaxaxa::SOLTCalibration::getSOLCoeffs (this=this@entry=0x5610a39f9a40, measurements=std::vector of length 3, capacity 3 = {...}, 
    calStdModels=std::vector of length 3, capacity 3 = {...}) at calibration.C:221

#8  0x00007f373e157309 in xaxaxa::SOLTCalibration::computeCoefficients (this=0x5610a39f9a40, measurements=std::vector of length 7, capacity 7 = {...}, 
    calStdModels=std::vector of length 7, capacity 7 = {...}) at calibration.C:152

```

**Comment by biergaizi** [comment]
Is Unknown Thru / UXYZ calibration even possible on a one-path (T/R) VNA like the NanoVNA V2? The NanoVNA-QT source code was what led me to initially believe it was possible in the old scikit-rf thread. But it appears that the algorithm doesn't actually run and the matrices are unsolvable, so it appears that Unknown Thru / UXYZ requires a full 2-path VNAs, and this option is suppose to be hidden in T/R mode. Is it correct? CC @mdkendall 

## Edit

This has already been answered in [this thread](https://github.com/xaxaxa-dev/vna/issues/20)

> Are you in T/R mode? The error message "matrix rank is not full" implies the measurements are not linearly independent, which can happen if you e.g. try to calibrate port 2 when in T/R mode.

Conclusion: It's *not possible* to use UXYZ / Modified UXYZ / Unknown Thru calibration on a T/R network analyzer, a full 2-port analyzer is required. Its appearance in NanoVNA-QT GUI is just a bug, this option should be hidden.
